require('setups.onedark');
-- require('setups.onenord');
require('setups.whichkey');
require('setups.lsp');
require('setups.telescope');
require('setups.treesitter');
require('setups.cmp');
require('setups.lualine');
require('setups.toggleterm');
-- require('setups.indent_blankline');
-- require('setups.dashboard');
